import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const appDir = fileURLToPath(new URL("..", import.meta.url));
const migrationsDir = path.join(appDir, "migrations");

const journal = JSON.parse(
  fs.readFileSync(path.join(migrationsDir, "meta/_journal.json"), "utf8"),
) as { entries: { idx: number; tag: string }[] };

const migrations = [...journal.entries]
  .sort((a, b) => a.idx - b.idx)
  .map((entry) => {
    const sql = fs.readFileSync(path.join(migrationsDir, `${entry.tag}.sql`), "utf8");
    const statements = sql
      .split("--> statement-breakpoint")
      .map((statement) => statement.trim())
      .filter(Boolean);
    return { id: entry.tag, statements };
  });

const header = "// generated by scripts/embed-migrations.ts — run `pnpm db:generate`, do not edit\n";
const body = `export const migrations: { id: string; statements: string[] }[] = ${JSON.stringify(migrations, null, 2)};\n`;
fs.writeFileSync(path.join(appDir, "src/db/migrations.gen.ts"), header + body);
console.log(`embedded ${migrations.length} migration(s) into src/db/migrations.gen.ts`);
