// generated by scripts/embed-migrations.ts — run `pnpm db:generate`, do not edit
export const migrations: { id: string; statements: string[] }[] = [
  {
    "id": "0000_third_agent_zero",
    "statements": [
      "CREATE TABLE `app_state` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL\n);",
      "CREATE TABLE `logs` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`session_id` text NOT NULL,\n\t`at` integer NOT NULL,\n\t`message` text NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE INDEX `logs_session_idx` ON `logs` (`session_id`,`id`);",
      "CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`sdk_session_id` text,\n\t`created_at` integer NOT NULL,\n\t`title` text DEFAULT '' NOT NULL,\n\t`model` text DEFAULT '' NOT NULL,\n\t`permission_mode` text DEFAULT 'default' NOT NULL,\n\t`cost_usd` real DEFAULT 0 NOT NULL,\n\t`items` text DEFAULT '[]' NOT NULL\n);"
    ]
  }
];
